Models/Cart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace bookstore.Models
{
    public class Cart
	{
		public Cart()
		{
		}

        public List<LineItem> Books { get; set; } = new List<LineItem>();

        public virtual void AddItem (Book book, int qty)
        {
            LineItem currentItem = Books
                .Where(b => b.Book.BookId == book.BookId)
                .FirstOrDefault();

            if (currentItem == null)
            {
                Books.Add(
                    new LineItem
                    {
                        Book = book,
                        Qty = qty
                    }
                );
            }
            else
            {
                currentItem.Qty += qty;
            }
        }

        public virtual void DecrementQty (Book book)
        {
            LineItem currentItem = Books
                .Where(l => l.Book.BookId == book.BookId)
                .FirstOrDefault();

            currentItem.Qty -= 1;

            if (currentItem.Qty < 1)
            {
                RemoveItem(book);
            }
        }

        public virtual void RemoveItem (Book book)
        {
            Books.RemoveAll(l => l.Book.BookId == book.BookId);
        }

        public virtual void ClearCart ()
        {
            Books.Clear();
        }

        public decimal GetSum()
        {
            return Books.Sum(book => book.Qty * (decimal) book.Book.Price);
        }
    }

	public class LineItem
    {
        [Key]
        public int LineItemId { get; set; }
        public int Qty { get; set; }
        public Book Book { get; set; }
    }
}

Controllers/CheckoutController.cs
using System;
using bookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace bookstore.Controllers
{
	public class CheckoutController: Controller
	{
		IBookstoreRepository _repo { get; set; }
		Cart _cart { get; set; }

		public CheckoutController(IBookstoreRepository repo, Cart cart)
		{
			_repo = repo;
			_cart = cart;
		}

		[HttpGet]
		public IActionResult Checkout()
        {
			//Do not let the user checkout if their cart is empty.
			if (_cart.Books.Count == 0)
				return RedirectToPage("/Cart");
			else
				ViewBag.OrderTotal = _cart.GetSum();
				return View(new Transaction());
        }

		[HttpPost]
		public IActionResult Checkout(Transaction t)
        {
			ViewBag.OrderTotal = _cart.GetSum();

			if (ModelState.IsValid)
            {
				t.LineItems = _cart.Books;
                try
                {
					_repo.SaveTransaction(t);
					_cart.ClearCart();
				}
				catch (Exception e)
                {
					Console.WriteLine(e);
					return RedirectToPage("/Error");
                }
				
				return RedirectToPage("/Success");
			}
            else
            {
				return View(t);
            }
        }
	}
}

Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using bookstore.Models;
using bookstore.Infrastructure;

namespace bookstore.Pages
{
    public class CartModel : PageModel
    {

        public IBookstoreRepository Repository { get; set; }
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }

        public CartModel(IBookstoreRepository repo, Cart cart)
        {
            Repository = repo;
            //what is it about the HTTPContext which disallows me from instantiating the cart here?
            Cart = cart;
            
        }

        public void OnGet(string _returnUrl) //this param name needs to match what will be in the URL, else it will always come back "/". 
        {
            ReturnUrl = _returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string ReturnUrl)
        {
            var book = Repository.BooksData
                .FirstOrDefault(book => book.BookId == bookId);

            Cart.AddItem(book, 1);

            return RedirectToPage( new { ReturnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string ReturnUrl)
        {
            Cart.RemoveItem(Cart.Books.First(l => l.Book.BookId == bookId).Book);
            return RedirectToPage(new { ReturnUrl });
        }
    }
}

Pages/Cart.cshtml
@page
@model bookstore.Pages.CartModel
@{
    ViewData["Title"] = "Cart";
}

<div class="container my-4 pt-4">
<h1>Cart</h1>


<table class="table table-hover table-bordered table-striped">
    <thead>
        <tr>
            <th scope="col">Book</th>
            <th scope="col">Quantity</th>
            <th scope="col">Cost</th>
            <th scope="col">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in @Model.Cart.Books)
        {
            <tr>
                <th scope="row">@book.Book.Title - @book.Book.Author</th>
                <td>@book.Qty</td>
                <td>$@(Math.Round(book.Book.Price, 2).ToString("#.00"))</td>
                <td>$@(Math.Round(book.Qty * book.Book.Price, 2).ToString("#.00"))</td>

                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@book.Book.BookId" />
                        <input type="hidden" name="ReturnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-small btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <th colspan="3">Total:</th>
        <td>$@(Math.Round(Model.Cart.GetSum(), 2).ToString("#.00"))</td>
    </tfoot>
</table>


<div class="d-flex justify-content-end">
    <a href="@Model.ReturnUrl" class="btn btn-secondary mx-4">Keep Shopping</a>
    <a asp-controller="Checkout" asp-action="Checkout" class="btn btn-primary" >Checkout</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</div>

Pages/Success.cshtml
@page
@{
}
<div class="container my-4 pt-4">
<div class="text-center my-4">
    <h2>Your books are on their way...</h2>
    <h4>For next time, make sure to check out <a asp-controller="Home" asp-action="Index" asp-route-category="Biography">these best-selling biographies!</a></h4>
    <a class="my-3 btn btn-primary" asp-controller="Home" asp-action="Index">Home</a>
</div>
</div>

Pages/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
</head>
<body>
    
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - bookstore
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    @*turn on tooltips for all razor pages inheriting this layout*@
    <script type="text/javascript">
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
</body>
</html>